<?php

declare(strict_types=1);
/**
 * @var $block \Avalon\Mtfibankpayment\Block\Adminhtml\Order\View\Tab\FibankTab
 */
?>

<?php if ($block->checkFibank()) { ?>
    <div>
        <div class="fieldset-wrapper-title">
            <span class="title">
                <?= $block->escapeHtml('Информация за плащане на поръчката с Fibank Credit покупки на Кредит') ?>
            </span>
        </div>
        <table class="admin__table-secondary">
            <tbody>
                <?= $block->getChildHtml(); ?>
                <tr>
                    <th><?= $block->escapeHtml('Поръчка № :') ?></th>
                    <td><?= $block->escapeHtml($block->getOrderIncrementId()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml('Състояние :') ?></th>
                    <td>
                        <span>
                            <?= $block->escapeHtml($block->getPaymentData('order_status')) ?>
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
<?php } else { ?>
    <div class="fieldset-wrapper order-information">
        <div class="fieldset-wrapper-title">
            <span class="title">
                <?= $block->escapeHtml('Няма извършено плащане с Fibank Credit покупки на Кредит') ?>
            </span>
        </div>
    </div>
<?php } ?>
